name: anki_pai
description: Memorization app with AI support.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase Core
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.2
  
  # Google Services
  google_sign_in: ^6.1.6
  google_mobile_ads: ^6.0.0  # Downgraded for compatibility
  
  # State Management
  provider: ^6.1.1
  get_it: ^7.6.7
  
  # UI Components
  flip_card: ^0.7.0
  dotted_border: ^2.1.0
  flutter_math_fork: ^0.7.3
  
  # Image & Media
  image_picker: ^1.0.7
  crop_your_image: ^2.0.0
  image: ^4.1.4
  cached_network_image: ^3.3.1
  
  # Storage & Local Data
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Network
  http: ^1.1.2
  dio: ^5.4.0
  url_launcher: ^6.2.2
  
  # Payment
  flutter_stripe: ^9.5.0+1
  stripe_android: ^9.5.0+1
  stripe_platform_interface: ^9.5.0+1
  
  # Utilities
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.2.2
  crypto: ^3.0.3
  connectivity_plus: ^5.0.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  
  # Payments
  in_app_purchase: ^3.1.15
  in_app_purchase_android: ^0.3.6+13
  in_app_purchase_storekit: ^0.3.6+1
  
  # Background Services
  flutter_background_service: ^5.0.3
  
  # App Tracking
  app_tracking_transparency: ^2.0.6
  
  # Splash Screen
  flutter_native_splash: ^2.4.4
  cloud_functions: ^4.7.6
  
  # Environment variables

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.10

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/.env
    - assets/images/
  fonts:
    - family: Rounded
      fonts:
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 100
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 200
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 300
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 400
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 600
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 700
        # - asset: assets/fonts/ZenMaruGothic-Medium.ttf
        #   weight: 500

# Override dependencies with versions compatible with macOS 10.15
dependency_overrides:
  # Fix for gRPC and BoringSSL-GRPC compatibility issues with macOS 10.15
  grpc: 3.1.0
  googleapis_auth: 1.4.1
  http2: 2.0.0
  http: ^1.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#E0F7FA"
    theme_color: "#E0F7FA"

flutter_native_splash:
  color: "#E0F7FA"
  image: "assets/images/splash.png"
